"""Stage-3 quality + license filters (#72).

Pure-Python; no backend, no network. Exercises each heuristic plus the composed
`build_corpus` path (which stays default-off so the #69 gate is unchanged).
"""

import pytest

from src.data.corpus import Record, build_corpus, filter_records
from src.data.filters import (DEFAULT_THRESHOLDS, FilterStats, QualityThresholds,
                              is_code_record, license_ok, looks_autogenerated,
                              looks_minified, scrub_secrets, text_quality_ok,
                              text_quality_reasons)

pytest.importorskip("pyarrow")  # only build_corpus end-to-end needs it


# --- license gating (code only) ------------------------------------------------------
def test_is_code_record_detection():
    assert is_code_record(Record("x", "the-stack", lang="python", license="mit"))
    assert is_code_record(Record("x", "src", lang="en", meta={"is_code": True}))
    assert not is_code_record(Record("x", "fineweb-edu", lang="en", license="odc-by"))


def test_license_ok_gates_code_not_text():
    # Non-permissive code dropped; permissive + flagged share-alike kept.
    assert not license_ok(Record("x", "the-stack", lang="python", license="GPL-3.0"))
    assert license_ok(Record("x", "the-stack", lang="python", license="Apache-2.0"))
    assert license_ok(Record("x", "the-stack", lang="rust", license="CC-BY-SA-4.0"))
    # Text is never license-excluded (even unknown) — obligations are tracked elsewhere.
    assert license_ok(Record("x", "fineweb-edu", lang="en", license="unknown"))


# --- text quality --------------------------------------------------------------------
def test_text_quality_accepts_prose():
    prose = ("The quick brown fox jumps over the lazy dog. " * 8).strip()
    assert text_quality_ok(prose), text_quality_reasons(prose)


def test_text_quality_rejects_junk():
    assert "too_short" in text_quality_reasons("hi there")
    assert "high_symbol" in text_quality_reasons("@#$%^&*() " * 40)
    assert "repetitive" in text_quality_reasons(("spam " * 80).strip())
    assert "high_digit" in text_quality_reasons(("1234567890 " * 40))


def test_quality_thresholds_are_tunable():
    th = QualityThresholds(min_chars=5, min_words=1)
    assert text_quality_ok("hello world", th)
    assert not text_quality_ok("hello world", DEFAULT_THRESHOLDS)  # default min_chars=200


# --- minified / autogenerated --------------------------------------------------------
def test_looks_minified():
    minified = "var a=1;" + "x".join(f"f{i}()" for i in range(400)) + ";"  # one long line
    assert looks_minified(minified)
    assert not looks_minified("def f():\n    return 1\n" * 50)


def test_looks_autogenerated():
    assert looks_autogenerated("// Code generated by protoc. DO NOT EDIT.\npackage x")
    assert looks_autogenerated("row\n" * 50)             # >80% duplicate lines
    assert not looks_autogenerated("def f():\n    return 1\n")


# --- secret / PII scrub --------------------------------------------------------------
def test_scrub_secrets_redacts_and_counts():
    text = ("contact me at jane.doe@example.com using AKIAIOSFODNN7EXAMPLE "
            "and api_key = 'sk-abc123def456ghi789'")
    out, n = scrub_secrets(text)
    assert n >= 3
    assert "jane.doe@example.com" not in out and "[EMAIL]" in out
    assert "AKIAIOSFODNN7EXAMPLE" not in out and "[AWS_KEY]" in out
    assert "sk-abc123def456ghi789" not in out and "[REDACTED]" in out


def test_scrub_noop_on_clean_text():
    out, n = scrub_secrets("nothing sensitive here at all")
    assert n == 0 and out == "nothing sensitive here at all"


# --- composed filter_records + stats -------------------------------------------------
def test_filter_records_stats_and_drops():
    recs = [
        Record("Curated educational text covering science history and many "
               "varied topics for readers. " * 8, "fineweb-edu", lang="en"),  # text, kept
        Record("def f(): return 1", "the-stack", lang="python", license="GPL-3.0"),  # code, license drop
        Record("@#$ " * 80, "fineweb-edu", lang="en"),                   # text, quality drop
    ]
    stats = FilterStats()
    out = list(filter_records(recs, quality=True, license_filter=True, stats=stats))
    assert len(out) == 1 and out[0].source == "fineweb-edu"
    assert stats.dropped_license == 1 and stats.dropped_quality == 1 and stats.kept == 1


def test_filter_records_scrub_modifies_text_and_meta():
    recs = [Record("reach me at bob@x.com now and then", "src", lang="en")]
    stats = FilterStats()
    out = list(filter_records(recs, scrub=True, stats=stats))
    assert "[EMAIL]" in out[0].text and out[0].meta["secrets_scrubbed"] == 1
    assert stats.docs_scrubbed == 1 and stats.secrets_scrubbed == 1


def test_build_corpus_default_off_is_unchanged(tmp_path):
    """Default build_corpus keeps the #69 behavior: only the length floor applies."""
    recs = [Record("w1 w2 w3 w4 w5", "dummy", license="synthetic") for _ in range(4)]
    shards = build_corpus(recs, tmp_path / "cleaned")
    from src.data.corpus import read_shards
    assert len(list(read_shards(tmp_path / "cleaned"))) == 4   # nothing dropped


def test_build_corpus_with_filters_drops_planted_bad_doc(tmp_path):
    recs = [
        Record("Real curated prose. " * 30, "fineweb-edu", lang="en"),
        Record("$$$ " * 100, "fineweb-edu", lang="en"),                  # quality drop
    ]
    stats = FilterStats()
    shards = build_corpus(recs, tmp_path / "cleaned", quality=True, stats=stats)
    from src.data.corpus import read_shards
    kept = list(read_shards(tmp_path / "cleaned"))
    assert len(kept) == 1 and stats.dropped_quality == 1
