"""Export a `--config` sidecar for `monica-bench` (#170) — a shapes-only, no-weights
JSON so the Swift bench harness can run poc-scale timing/memory sweeps without checking
in a ~500 MB safetensors artifact.

Writes exactly the `MambaConfig.to_dict()` JSON `src/train/checkpoint.py:save_weights`
puts in a real `<weights>.config.json` sidecar — the same shape `MambaConfig.load
(sidecar:)` (Swift) already knows how to decode, so `monica-bench --config <out>.json`
needs no format of its own.

    .venv/bin/python scripts/export_bench_config.py --config config/poc.yaml \\
        --out swift/engine/Benchmarks/configs/poc.config.json

The checked-in `swift/engine/Benchmarks/configs/*.json` are regenerated by this exact
command — `tests/test_bench_config_export.py` re-runs it and asserts no diff, the same
"the checked-in artifact cannot go stale" pattern `tests/test_parity_fixture_export.py`
uses for the parity fixtures.

Portable: only reads `MambaConfig`/`load_config` (numpy/dataclass, no MLX/torch), so it
runs on any host, including the `portable` CI job.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from src.model.blocks import load_config


def export_bench_config(config_path: str, out_path: str) -> None:
    cfg = load_config(config_path)
    Path(out_path).parent.mkdir(parents=True, exist_ok=True)
    Path(out_path).write_text(json.dumps(cfg.to_dict(), indent=2, default=str) + "\n")


def _parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--config", type=Path, required=True, help="e.g. config/poc.yaml")
    ap.add_argument("--out", type=Path, required=True,
                    help="e.g. swift/engine/Benchmarks/configs/poc.config.json")
    return ap.parse_args()


def main() -> None:
    args = _parse_args()
    export_bench_config(str(args.config), str(args.out))
    print(f"[export_bench_config] wrote {args.out} from {args.config}")


if __name__ == "__main__":
    main()
