"""Scale corpus pipeline on HF datatrove (#80) — the pod/cluster port of the laptop-scale
`src/data/` stages.

The offline stages (`corpus.py` / `filters.py` / `dedup.py`) are "the laptop-scale version of
the datatrove pipeline" (docs/design/08-corpus-pipeline.md): same common schema
`{text, source, lang, license, meta}`, same six-stage shape. This module is the **port onto
datatrove** so the full-source build (FineWeb-Edu + supplements, cross-source MinHash) runs on a
CPU pod, while **reusing** the project filter/dedup *logic* rather than re-deriving it:

    HuggingFaceDatasetReader        ingest (FineWeb-Edu first; sources are config-driven)
      -> LicenseFilter              filters.license_ok          (permissive-only on code)
      -> QualityFilter              filters.text_quality_ok     (FineWeb/Gopher-style heuristics)
      -> MinifiedAutogenFilter      filters.looks_minified / looks_autogenerated
      -> DecontaminationFilter      dedup.Decontaminator        (13/7-gram benchmark overlap)
      -> SecretScrubber             filters.scrub_secrets       (mapper: redacts secrets/PII)
      -> JsonlWriter                cleaned text shards under <out>/cleaned
    [then] datatrove-native MinHash dedup (the distributed win) -> <out>/dedup

The datatrove/our-code boundary stops at **cleaned text**: the existing `tokenize.py`/`pack.py`/
`shard.py` turn cleaned shards into the Qwen3 uint32 trainer shards (trainer format unchanged).

ABOVE THE SEAM — datatrove has **no torch dependency**, and every datatrove import here is **lazy**
(inside functions / a block factory) so the module imports cleanly on the main py3.14 env where
datatrove isn't installed (the seam guard imports it there). datatrove runs in the dedicated py3.11
venv (`.venv-dt`) that matches the RunPod images; `tests/test_datatrove_pipeline.py` skips where it
is absent.
"""

from __future__ import annotations

from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]

from . import storage
from .corpus import Record
from .filters import (DEFAULT_THRESHOLDS, QualityThresholds, license_ok, looks_autogenerated,
                      looks_minified, scrub_secrets, text_quality_ok)

#: FineWeb-Edu on the Hub (curated web-text spine, ODC-BY) — the first concrete source (#70).
FINEWEB_EDU_DATASET = "HuggingFaceFW/fineweb-edu"


def to_record(doc) -> Record:
    """A `filters`/`dedup` Record view of a datatrove Document (schema lives in `doc.metadata`)."""
    md = doc.metadata or {}
    return Record(text=doc.text, source=md.get("source", ""), lang=md.get("lang", "en"),
                  license=md.get("license", "unknown"), meta=md)


def _folder(uri):
    """A datatrove output_folder spec for an fsspec URI. For `s3://` inject the R2 endpoint from the
    env (key/secret come from `AWS_*` via s3fs); local paths pass through unchanged."""
    if str(uri).startswith("s3://"):
        import os
        from .r2_sync import r2_endpoint
        endpoint = r2_endpoint()
        if endpoint:
            return (
                str(uri),
                {
                    "client_kwargs": {
                        "endpoint_url": endpoint,
                        "region_name": os.environ.get("AWS_DEFAULT_REGION", "auto"),
                    }
                },
            )
    return str(uri)


def _custom_blocks(thresholds: QualityThresholds = DEFAULT_THRESHOLDS):
    """Define the project's filter/scrub blocks as datatrove steps (lazy import). Returns a dict of
    the block classes so `clean_pipeline` can instantiate the enabled ones."""
    from datatrove.pipeline.base import PipelineStep
    from datatrove.pipeline.filters.base_filter import BaseFilter

    class LicenseFilter(BaseFilter):
        """Keep text always; keep code only under a permissive / flagged-share-alike license."""
        name = "🔑 license"

        def filter(self, doc):
            return license_ok(to_record(doc))

    class QualityFilter(BaseFilter):
        """Drop gross-junk TEXT (curated code passes); reuses `filters.text_quality_ok`."""
        name = "✨ quality"

        def filter(self, doc):
            rec = to_record(doc)
            from .filters import is_code_record
            if is_code_record(rec):
                return True
            return text_quality_ok(doc.text, thresholds)

    class MinifiedAutogenFilter(BaseFilter):
        """Drop minified / autogenerated CODE."""
        name = "🧹 minified/autogen"

        def filter(self, doc):
            rec = to_record(doc)
            from .filters import is_code_record
            if not is_code_record(rec):
                return True
            return not (looks_minified(doc.text) or looks_autogenerated(doc.text))

    class DecontaminationFilter(BaseFilter):
        """Drop docs whose 13/7-gram windows overlap the eval benchmarks (`dedup.Decontaminator`)."""
        name = "🧴 decontaminate"

        def __init__(self, decontaminator, **kw):
            super().__init__(**kw)
            self._decon = decontaminator

        def filter(self, doc):
            is_contam = self._decon.contaminated(doc.text)
            if is_contam:
                self.stat_update("dropped_decontam")
                return False
            return True

    class SecretScrubber(PipelineStep):
        """Mapper: redact secrets/PII in place (`filters.scrub_secrets`), tag count in metadata."""
        name = "🔒 scrub"

        def run(self, data, rank: int = 0, world_size: int = 1):
            for doc in data:
                scrubbed, n = scrub_secrets(doc.text)
                if n:
                    doc.text = scrubbed
                    if doc.metadata is None:                # datatrove docs may carry metadata=None
                        doc.metadata = {}
                    doc.metadata["secrets_scrubbed"] = doc.metadata.get("secrets_scrubbed", 0) + n
                    self.stat_update("docs_scrubbed")
                    self.stat_update("secrets_scrubbed", value=n)
                yield doc

    class PrettierFormatter(PipelineStep):
        """Mapper: format TypeScript / JavaScript code with prettier to standardize syntax and minimize token entropy (#419)."""
        name = "💅 prettier"

        def __init__(self, prettier_argv: Optional[List[str]] = None, parser: str = "typescript", **kw):
            super().__init__(**kw)
            self._prettier_argv = prettier_argv
            self._parser = parser

        def run(self, data, rank: int = 0, world_size: int = 1):
            from src.lsp.prettier import format_source, resolve_prettier
            argv = self._prettier_argv if self._prettier_argv is not None else resolve_prettier()
            for doc in data:
                rec = to_record(doc)
                from .filters import is_code_record
                lang = (doc.metadata or {}).get("lang", "") or getattr(rec, "lang", "")
                if argv is not None and (lang in ("typescript", "javascript", "ts", "js", "tsx", "jsx") or (is_code_record(rec) and not lang)):
                    formatted = format_source(doc.text, argv, parser=self._parser)
                    if formatted != doc.text:
                        doc.text = formatted
                        if doc.metadata is None:
                            doc.metadata = {}
                        doc.metadata["prettier_formatted"] = True
                        self.stat_update("formatted_docs")
                yield doc

    return {
        "LicenseFilter": LicenseFilter,
        "QualityFilter": QualityFilter,
        "MinifiedAutogenFilter": MinifiedAutogenFilter,
        "DecontaminationFilter": DecontaminationFilter,
        "SecretScrubber": SecretScrubber,
        "PrettierFormatter": PrettierFormatter,
    }


def fineweb_edu_reader(*, limit: int = -1, streaming: bool = True, split: str = "train"):
    """A datatrove reader over FineWeb-Edu, tagged with the common-schema source/lang/license so the
    downstream filters key on it identically to the local path. `limit<0` means no cap."""
    from datatrove.pipeline.readers import HuggingFaceDatasetReader
    return HuggingFaceDatasetReader(
        dataset=FINEWEB_EDU_DATASET,
        dataset_options={"split": split},
        streaming=streaming,
        limit=limit,
        text_key="text",
        id_key="id",
        default_metadata={"source": "fineweb-edu", "lang": "en", "license": "odc-by"},
    )


def jsonl_reader(path, *, limit: int = -1, text_key: str = "text",
                 id_key: str = "id", default_metadata: dict | None = None,
                 glob_pattern: str | None = None):
    """A datatrove reader over a local JSONL file or directory of JSONL files."""
    from datatrove.pipeline.readers import JsonlReader
    pat = glob_pattern
    if pat is None:
        p_str = str(path)
        if not p_str.endswith(".jsonl") and not p_str.endswith(".jsonl.gz"):
            pat = "*.jsonl*"
    return JsonlReader(
        data_folder=str(path),
        limit=limit,
        text_key=text_key,
        id_key=id_key,
        default_metadata=default_metadata,
        glob_pattern=pat,
    )


def clean_pipeline(reader, out_uri, *, quality: bool = False, license_filter: bool = False,
                   drop_minified: bool = False, drop_autogen: bool = False, scrub: bool = False,
                   prettier: bool = False, prettier_argv: Optional[List[str]] = None,
                   decontaminator=None, thresholds: QualityThresholds = DEFAULT_THRESHOLDS,
                   output_filename: str = "${rank}.jsonl.gz",
                   compression: str | None = "gzip") -> list:
    """Stages 2–5 as a datatrove pipeline: reader -> enabled filters/scrub/prettier/decontam -> cleaned JSONL shards
    under `<out_uri>/cleaned`. `out_uri` is a `storage.py` class root (`file://` local,
    `s3://monica-training/...` on a pod). Filters are opt-in, mirroring `corpus.build_corpus`."""
    from datatrove.pipeline.writers import JsonlWriter

    blocks = _custom_blocks(thresholds)
    steps: list = [reader]
    if license_filter:
        steps.append(blocks["LicenseFilter"]())
    if quality:
        steps.append(blocks["QualityFilter"]())
    if drop_minified or drop_autogen:
        steps.append(blocks["MinifiedAutogenFilter"]())
    if scrub:
        steps.append(blocks["SecretScrubber"]())
    if prettier:
        steps.append(blocks["PrettierFormatter"](prettier_argv=prettier_argv))
    if decontaminator is not None:
        steps.append(blocks["DecontaminationFilter"](decontaminator))
    cleaned_dir = f"{str(out_uri).rstrip('/')}/cleaned"
    steps.append(JsonlWriter(output_folder=_folder(cleaned_dir), output_filename=output_filename,
                             compression=compression))
    return steps


def make_executor(pipeline: list, logging_dir, *, kind: str = "local", tasks: int = 1,
                  workers: int = 1, depends=None, **slurm_kwargs):
    """Wrap a pipeline in an executor. `kind="local"` -> LocalPipelineExecutor (Mac / single pod);
    `kind="slurm"` -> SlurmPipelineExecutor (cluster). `depends` chains multi-stage runs."""
    if kind == "local":
        from datatrove.executor import LocalPipelineExecutor
        return LocalPipelineExecutor(pipeline=pipeline, logging_dir=str(logging_dir),
                                     tasks=tasks, workers=workers, depends=depends)
    if kind == "slurm":
        from datatrove.executor import SlurmPipelineExecutor
        return SlurmPipelineExecutor(pipeline=pipeline, logging_dir=str(logging_dir),
                                     tasks=tasks, depends=depends, **slurm_kwargs)
    raise ValueError(f"unknown executor kind {kind!r} (use 'local' or 'slurm')")


def minhash_config(*, num_buckets: int = 14, hashes_per_bucket: int = 8, precision: int = 64):
    """datatrove MinhashConfig (the LSH banding that sizes the dedup)."""
    from datatrove.pipeline.dedup.minhash import MinhashConfig
    from datatrove.utils.hashing import HashConfig
    return MinhashConfig(hash_config=HashConfig(precision=precision),
                         num_buckets=num_buckets, hashes_per_bucket=hashes_per_bucket)


def run_minhash_dedup(cleaned_uri, base_uri, *, kind: str = "local", tasks: int = 1,
                      workers: int = 1, config=None, logging_dir=None) -> dict:
    """The standard datatrove 4-stage cross-source MinHash dedup, run end to end over the cleaned
    JSONL at `cleaned_uri`. Intermediates + the deduplicated output live under `base_uri`:
    `signatures/ buckets/ remove_ids/ deduplicated/`. Each stage `depends=` the previous one.
    Returns deduplication statistics dict recording document and repository metrics (#419)."""
    import glob
    import gzip
    import json
    from datatrove.pipeline.dedup import (MinhashDedupBuckets, MinhashDedupCluster,
                                          MinhashDedupFilter, MinhashDedupSignature)
    from datatrove.pipeline.readers import JsonlReader
    from datatrove.pipeline.writers import JsonlWriter
    from .r2_sync import _fs_for

    cfg = config or minhash_config()
    base = str(base_uri).rstrip("/")
    logging_dir = str(logging_dir or f"{base}/logs")
    sig, buckets, ids, out = (f"{base}/signatures", f"{base}/buckets",
                              f"{base}/remove_ids", f"{base}/deduplicated")

    # datatrove's fixed stage-task topology: signatures + filter run one task per input shard;
    # buckets MUST run exactly num_buckets tasks (it shards by bucket); clustering is single-task.
    s1 = make_executor([JsonlReader(_folder(cleaned_uri)),
                        MinhashDedupSignature(output_folder=_folder(sig), config=cfg)],
                       f"{logging_dir}/sig", kind=kind, tasks=tasks, workers=workers)
    s2 = make_executor([MinhashDedupBuckets(input_folder=_folder(sig),
                                            output_folder=_folder(buckets), config=cfg)],
                       f"{logging_dir}/buckets", kind=kind, tasks=cfg.num_buckets,
                       workers=workers, depends=s1)
    s3 = make_executor([MinhashDedupCluster(input_folder=_folder(buckets),
                                            output_folder=_folder(ids), config=cfg)],
                       f"{logging_dir}/cluster", kind=kind, tasks=1, workers=1, depends=s2)
    s4 = make_executor([JsonlReader(_folder(cleaned_uri)),
                        MinhashDedupFilter(input_folder=_folder(ids),
                                           exclusion_writer=JsonlWriter(_folder(f"{base}/removed"))),
                        JsonlWriter(output_folder=_folder(out))],
                       f"{logging_dir}/filter", kind=kind, tasks=tasks, workers=workers, depends=s3)
    s4.run()

    # Collect deduplication statistics across files and repositories (#419)
    fs, root_base = _fs_for(base)
    out_dir = f"{root_base}/deduplicated"
    removed_dir = f"{root_base}/removed"

    def _scan_folder(folder):
        count = 0
        repos = set()
        try:
            files = fs.find(folder) if hasattr(fs, "find") else glob.glob(f"{folder}/**/*.jsonl*", recursive=True)
        except Exception:
            files = glob.glob(f"{folder}/**/*.jsonl*", recursive=True)
        for fp in files:
            fname = str(fp)
            if not fname.endswith(".jsonl") and not fname.endswith(".jsonl.gz"):
                continue
            try:
                open_fn = gzip.open if fname.endswith(".gz") else open
                with fs.open(fp, "rt", encoding="utf-8") if hasattr(fs, "open") and str(base).startswith("s3://") else open_fn(fp, "rt", encoding="utf-8") as f:
                    for line in f:
                        if line.strip():
                            count += 1
                            try:
                                d = json.loads(line)
                                r = (d.get("metadata") or {}).get("repo") or d.get("repo")
                                if r:
                                    repos.add(r)
                            except Exception:
                                pass
            except Exception:
                pass
        return count, repos

    n_after, repos_after = _scan_folder(out_dir)
    n_dropped, repos_removed = _scan_folder(removed_dir)
    repos_before = repos_after | repos_removed
    n_before = n_after + n_dropped
    drop_rate = round(n_dropped / n_before, 4) if n_before > 0 else 0.0
    duplicate_repos_removed = len(repos_before - repos_after)

    return {
        "applied": True,
        "method": "minhash_lsh",
        "n_before_dedup": n_before,
        "n_after_dedup": n_after,
        "dropped_duplicates": n_dropped,
        "drop_rate": drop_rate,
        "repos_before_dedup": len(repos_before),
        "repos_after_dedup": len(repos_after),
        "duplicate_repos_removed": duplicate_repos_removed,
        "duplicate_files_removed": n_dropped,
    }


def _download_swh_blob(blob_id: str, src_encoding: str = "utf-8", s3_client=None, s3_fs=None) -> str:
    """Fetch and gzip-decompress a blob from Software Heritage S3 (#418)."""
    if s3_client is not None:
        from .stack_v2 import download_contents
        return download_contents(blob_id, src_encoding, s3_client=s3_client)

    import gzip
    if s3_fs is None:
        import s3fs
        s3_fs = s3fs.S3FileSystem(
            anon=True,
            client_kwargs={"region_name": "us-east-1", "endpoint_url": "https://s3.amazonaws.com"},
        )
    with s3_fs.open(f"softwareheritage/content/{blob_id}", "rb") as f:
        body = gzip.decompress(f.read())
    return body.decode(src_encoding, errors="replace")


def stack_v2_reader(
    *,
    limit: int = -1,
    config: str = "TypeScript",
    lang: str = "typescript",
    files: Optional[Sequence[str]] = None,
    rows: Optional[Iterable[Dict[str, Any]]] = None,
    s3_client=None,
    s3_fs=None,
    batch_size: int = 1000,
    threads: int = 16,
):
    """A Datatrove reader over Stack v2 metadata + Software Heritage S3 content (#418).
    Enforces permissive license filtering before fetching content, and tags documents
    with language, license, repo, and blob metadata."""
    from datatrove.pipeline.readers.base import BaseReader
    from datatrove.data import Document
    from .filters import is_permissive, normalize_license

    class StackV2Reader(BaseReader):
        name = "📚 Stack v2"

        def __init__(self, limit: int = -1, skip: int = 0):
            super().__init__(limit=limit, skip=skip)
            self.limit = limit
            self._s3_fs = s3_fs

        def run(self, data=None, rank: int = 0, world_size: int = 1):
            if data:
                yield from data

            nonlocal s3_fs
            if s3_fs is None and s3_client is None and rows is None:
                import s3fs
                self._s3_fs = s3fs.S3FileSystem(
                    anon=True,
                    client_kwargs={"region_name": "us-east-1", "endpoint_url": "https://s3.amazonaws.com"},
                )

            count = 0
            if rows is not None:
                for i, row in enumerate(rows):
                    if world_size > 1 and (i % world_size) != rank:
                        continue
                    if self.limit >= 0 and count >= self.limit:
                        break

                    licenses = row.get("detected_licenses") or row.get("license") or []
                    if isinstance(licenses, str):
                        licenses = [licenses]
                    lic = normalize_license(licenses[0] if licenses else "")
                    if not is_permissive(lic):
                        continue
                    if row.get("is_vendor") or row.get("is_generated"):
                        continue

                    if "text" in row:
                        text = row["text"]
                    elif "content" in row:
                        text = row["content"]
                    elif "blob_id" in row:
                        try:
                            text = _download_swh_blob(
                                row["blob_id"],
                                row.get("src_encoding") or "utf-8",
                                s3_client=s3_client,
                                s3_fs=self._s3_fs,
                            )
                        except Exception:
                            self.stat_update("fetch_failed")
                            continue
                    else:
                        continue

                    doc = Document(
                        text=text,
                        id=f"stack_v2/{row.get('blob_id', i)}",
                        metadata={
                            "source": "stack-v2",
                            "lang": lang,
                            "license": lic,
                            "is_code": True,
                            "repo": row.get("repo_name", ""),
                            "path": row.get("path", ""),
                            "blob_id": row.get("blob_id", ""),
                        },
                    )
                    self.update_doc_stats(doc)
                    self.stat_update("documents")
                    count += 1
                    yield doc
                return

            import pyarrow.parquet as pq
            import fsspec
            from concurrent.futures import ThreadPoolExecutor
            from .vocab_sample import metadata_ok, STACK_V2_REPO

            target_files = list(files) if files else None
            if not target_files:
                fs_hf = fsspec.filesystem("hf")
                lang_dir = f"{STACK_V2_REPO}/data/{config}"
                target_files = sorted(
                    p for p in fs_hf.ls(lang_dir, detail=False) if p.endswith(".parquet")
                )

            shard_files = target_files[rank::world_size] if world_size > 1 else target_files
            columns = [
                "blob_id", "src_encoding", "detected_licenses", "length_bytes",
                "is_vendor", "is_generated", "path", "repo_name"
            ]

            def _fetch_row(r):
                try:
                    blob = r["blob_id"]
                    t = _download_swh_blob(
                        blob,
                        r.get("src_encoding") or "utf-8",
                        s3_client=s3_client,
                        s3_fs=self._s3_fs,
                    )
                    return r, t
                except Exception:
                    return r, None

            for pf_path in shard_files:
                if self.limit >= 0 and count >= self.limit:
                    break
                try:
                    if str(pf_path).startswith("datasets/"):
                        pf_obj = fsspec.filesystem("hf").open(pf_path)
                    else:
                        pf_obj = pf_path
                    pf = pq.ParquetFile(pf_obj)
                except Exception as e:
                    self.stat_update(f"open_failed_{type(e).__name__}")
                    continue

                for batch in pf.iter_batches(batch_size=batch_size, columns=columns):
                    if self.limit >= 0 and count >= self.limit:
                        break
                    batch_rows = [r for r in batch.to_pylist() if metadata_ok(r)]
                    if not batch_rows:
                        continue

                    with ThreadPoolExecutor(max_workers=threads) as pool:
                        results = pool.map(_fetch_row, batch_rows)
                        for r, text in results:
                            if self.limit >= 0 and count >= self.limit:
                                break
                            if not text:
                                self.stat_update("fetch_failed")
                                continue
                            licenses = r.get("detected_licenses") or []
                            lic = normalize_license(licenses[0] if licenses else "")
                            blob_id = r["blob_id"]
                            doc = Document(
                                text=text,
                                id=f"stack_v2/{blob_id}",
                                metadata={
                                    "source": "stack-v2",
                                    "lang": lang,
                                    "license": lic,
                                    "is_code": True,
                                    "repo": r.get("repo_name", ""),
                                    "path": r.get("path", ""),
                                    "blob_id": blob_id,
                                },
                            )
                            self.update_doc_stats(doc)
                            self.stat_update("documents")
                            count += 1
                            yield doc

    return StackV2Reader(limit=limit)


def essential_web_reader(
    *,
    limit: int = -1,
    files: Optional[Sequence[str]] = None,
    rows: Optional[Iterable[Dict[str, Any]]] = None,
    batch_size: int = 1000,
):
    """A Datatrove reader over Essential-Web v1.0 prose corpus (#418)."""
    from datatrove.pipeline.readers.base import BaseReader
    from datatrove.data import Document

    class EssentialWebReader(BaseReader):
        name = "🌐 Essential-Web"

        def __init__(self, limit: int = -1, skip: int = 0):
            super().__init__(limit=limit, skip=skip)
            self.limit = limit

        def run(self, data=None, rank: int = 0, world_size: int = 1):
            if data:
                yield from data

            count = 0
            if rows is not None:
                for i, row in enumerate(rows):
                    if world_size > 1 and (i % world_size) != rank:
                        continue
                    if self.limit >= 0 and count >= self.limit:
                        break

                    text = row.get("text", "")
                    if not text or not text.strip():
                        continue

                    doc = Document(
                        text=text,
                        id=f"essential_web/{row.get('id', i)}",
                        metadata={
                            "source": "essential-web",
                            "lang": "en",
                            "license": "odc-by",
                            "is_code": False,
                            "url": row.get("url", ""),
                        },
                    )
                    self.update_doc_stats(doc)
                    self.stat_update("documents")
                    count += 1
                    yield doc
                return

            import pyarrow.parquet as pq
            import fsspec
            from .vocab_sample import ESSENTIAL_WEB_DIR

            target_files = list(files) if files else None
            if not target_files:
                fs_hf = fsspec.filesystem("hf")
                target_files = sorted(
                    p for p in fs_hf.ls(ESSENTIAL_WEB_DIR, detail=False) if p.endswith(".parquet")
                )

            shard_files = target_files[rank::world_size] if world_size > 1 else target_files
            for pf_path in shard_files:
                if self.limit >= 0 and count >= self.limit:
                    break
                try:
                    if str(pf_path).startswith("datasets/"):
                        pf_obj = fsspec.filesystem("hf").open(pf_path)
                    else:
                        pf_obj = pf_path
                    pf = pq.ParquetFile(pf_obj)
                except Exception as e:
                    self.stat_update(f"open_failed_{type(e).__name__}")
                    continue

                col_candidates = [c for c in ("id", "text", "url") if c in pf.schema.names]
                for batch in pf.iter_batches(batch_size=batch_size, columns=col_candidates):
                    if self.limit >= 0 and count >= self.limit:
                        break
                    batch_rows = batch.to_pylist()
                    for row in batch_rows:
                        if self.limit >= 0 and count >= self.limit:
                            break
                        text = row.get("text", "")
                        if not text or not text.strip():
                            continue

                        doc_id = str(row.get("id") or f"{count}")
                        doc = Document(
                            text=text,
                            id=f"essential_web/{doc_id}",
                            metadata={
                                "source": "essential-web",
                                "lang": "en",
                                "license": "odc-by",
                                "is_code": False,
                                "url": row.get("url", ""),
                            },
                        )
                        self.update_doc_stats(doc)
                        self.stat_update("documents")
                        count += 1
                        yield doc

    return EssentialWebReader(limit=limit)


def composite_reader(readers: list):
    """A Datatrove reader chaining multiple readers in sequence (#418)."""
    from datatrove.pipeline.readers.base import BaseReader

    class CompositeReader(BaseReader):
        name = "🔗 CompositeReader"

        def __init__(self, readers_list):
            super().__init__()
            self.readers_list = readers_list

        def run(self, data=None, rank: int = 0, world_size: int = 1):
            if data:
                yield from data
            for r in self.readers_list:
                yield from r.run(rank=rank, world_size=world_size)

    return CompositeReader(readers)


def raw_extraction_pipeline(
    reader,
    out_uri: str,
    *,
    output_filename: str = "${rank}.jsonl",
) -> list:
    """A Datatrove pipeline for raw document extraction (#418):
    reader -> JsonlWriter(output_folder=_folder(out_uri), output_filename=output_filename, compression=None).
    Emits raw uncompressed .jsonl files."""
    from datatrove.pipeline.writers import JsonlWriter

    return [
        reader,
        JsonlWriter(
            output_folder=_folder(out_uri),
            output_filename=output_filename,
            compression=None,
        ),
    ]


def generate_extraction_manifest(out_uri: str) -> dict:
    """Scan emitted uncompressed .jsonl shards in out_uri and write manifest.json recording
    total volume, document count, and source breakdown (#418)."""
    import json
    import time
    from .r2_sync import _fs_for

    fs, root = _fs_for(out_uri)
    root = root.rstrip("/")

    total_volume_bytes = 0
    total_docs = 0
    source_breakdown = {}
    shards_found = []

    try:
        found_files = fs.find(root)
    except Exception:
        found_files = []

    for fpath in sorted(found_files):
        fname = fpath.rsplit("/", 1)[-1]
        if not fname.endswith(".jsonl") or fname == "manifest.json":
            continue
        shards_found.append(fname)
        with fs.open(fpath, "r", encoding="utf-8") as fh:
            for line in fh:
                if not line.strip():
                    continue
                total_docs += 1
                line_bytes = len(line.encode("utf-8"))
                total_volume_bytes += line_bytes

                try:
                    doc_data = json.loads(line)
                except Exception:
                    continue

                md = doc_data.get("metadata") or {}
                source = md.get("source") or ("stack-v2" if "stack_v2" in fname else "essential-web" if "essential_web" in fname else "unknown")
                lang = md.get("lang") or ("typescript" if source == "stack-v2" else "en")
                lic = md.get("license") or ("mit" if source == "stack-v2" else "odc-by")

                if source not in source_breakdown:
                    source_breakdown[source] = {
                        "document_count": 0,
                        "total_bytes": 0,
                        "languages": {},
                        "licenses": {},
                        "files": set(),
                    }
                st = source_breakdown[source]
                st["document_count"] += 1
                st["total_bytes"] += line_bytes
                st["languages"][lang] = st["languages"].get(lang, 0) + 1
                st["licenses"][lic] = st["licenses"].get(lic, 0) + 1
                st["files"].add(fname)

    formatted_breakdown = {}
    for src, info in sorted(source_breakdown.items()):
        formatted_breakdown[src] = {
            "document_count": info["document_count"],
            "total_bytes": info["total_bytes"],
            "primary_language": max(info["languages"].items(), key=lambda x: x[1])[0] if info["languages"] else "unknown",
            "languages": info["languages"],
            "licenses": info["licenses"],
            "files": sorted(info["files"]),
        }

    manifest = {
        "total_volume_bytes": total_volume_bytes,
        "total_bytes": total_volume_bytes,
        "total_documents": total_docs,
        "document_count": total_docs,
        "source_breakdown": formatted_breakdown,
        "sources": formatted_breakdown,
        "shards": shards_found,
        "compression": "none",
        "format": "jsonl",
        "destination_uri": str(out_uri),
        "timestamp": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
    }

    manifest_json = json.dumps(manifest, indent=2)
    manifest_path = f"{root}/manifest.json"
    if str(out_uri).startswith("s3://"):
        fs.pipe(manifest_path, manifest_json.encode("utf-8"))
    else:
        with open(manifest_path, "w", encoding="utf-8") as mf:
            mf.write(manifest_json)

    return manifest


def run_raw_extraction(
    out_uri: str = "s3://monica-training/data/raw",
    *,
    stack_v2_limit: int = 1000,
    essential_web_limit: int = 1000,
    executor_kind: str = "local",
    tasks: int = 1,
    workers: int = 1,
    logging_dir: str | None = None,
    stack_v2_rows=None,
    essential_web_rows=None,
    stack_v2_files=None,
    essential_web_files=None,
    s3_client=None,
    s3_fs=None,
) -> dict:
    """Run the Datatrove ingestion pipeline to pull and extract raw uncompressed source
    documents (Stack v2 TypeScript subset + Essential-Web) to out_uri (Cloudflare R2 or local)
    and emit the document manifest recording volume and source breakdown (#418)."""
    import os
    import time

    logging_dir = str(logging_dir or f"/tmp/monica_raw_extraction_logs_{int(time.time())}")
    os.makedirs(logging_dir, exist_ok=True)

    if stack_v2_limit != 0:
        s_reader = stack_v2_reader(
            limit=stack_v2_limit,
            rows=stack_v2_rows,
            files=stack_v2_files,
            s3_client=s3_client,
            s3_fs=s3_fs,
        )
        s_pipe = raw_extraction_pipeline(s_reader, out_uri, output_filename="stack_v2_${rank}.jsonl")
        s_exec = make_executor(s_pipe, f"{logging_dir}/stack_v2", kind=executor_kind, tasks=tasks, workers=workers)
        s_exec.run()

    if essential_web_limit != 0:
        ew_reader = essential_web_reader(
            limit=essential_web_limit,
            rows=essential_web_rows,
            files=essential_web_files,
        )
        ew_pipe = raw_extraction_pipeline(ew_reader, out_uri, output_filename="essential_web_${rank}.jsonl")
        ew_exec = make_executor(ew_pipe, f"{logging_dir}/essential_web", kind=executor_kind, tasks=tasks, workers=workers)
        ew_exec.run()

    manifest = generate_extraction_manifest(out_uri)
    return manifest


def load_eval_decontaminator(
    blocklist_path: str | Path | None = None,
    eval_sets: Optional[Sequence[str]] = None,
    ngram_sizes: Tuple[int, ...] = (13, 7),
    prettier_argv: Optional[List[str]] = None,
) -> Tuple[Any, Optional[Path], List[str]]:
    """Load or build a Decontaminator targeting evaluation benchmarks (humaneval_ts and ts_error_injection) (#419).

    If blocklist_path is provided and exists, reads the n-gram lines directly.
    Otherwise, inspects eval_sets (defaulting to eval_sets/humaneval_ts and eval_sets/ts_error_injection)
    and constructs a Decontaminator from their prompts, test fixtures, and gold completions,
    optionally applying Prettier syntax normalization to code benchmarks so that AST matches are captured.
    """
    import json
    from .dedup import Decontaminator

    target_eval_sets = list(eval_sets) if eval_sets is not None else [
        "eval_sets/humaneval_ts",
        "eval_sets/ts_error_injection",
    ]

    resolved_path = None
    if blocklist_path is not None:
        p = Path(blocklist_path)
        if p.exists():
            resolved_path = p
    elif (REPO_ROOT / "eval_sets/decontam/blocklist.txt").exists():
        resolved_path = REPO_ROOT / "eval_sets/decontam/blocklist.txt"

    if resolved_path is not None and resolved_path.exists():
        with open(resolved_path, "r", encoding="utf-8") as f:
            decon = Decontaminator.from_texts((line.rstrip("\n") for line in f if line.strip()), ngram_sizes=ngram_sizes)
        return decon, resolved_path, target_eval_sets

    # Build dynamically from evaluation sets
    texts: List[str] = []
    p_argv = prettier_argv
    if p_argv is None:
        try:
            from src.lsp.prettier import resolve_prettier
            p_argv = resolve_prettier()
        except Exception:
            p_argv = None

    for es in target_eval_sets:
        p = REPO_ROOT / es
        if not p.exists():
            p = Path(es)
        if not p.exists():
            continue

        jsonl_files = [p] if p.is_file() else sorted(p.glob("*.jsonl"))
        for jf in jsonl_files:
            try:
                with open(jf, "r", encoding="utf-8") as f:
                    for line in f:
                        if not line.strip():
                            continue
                        row = json.loads(line)
                        for field in ("prompt", "tests", "gold_completion", "suffix", "answer", "text"):
                            val = row.get(field)
                            if val and isinstance(val, str) and len(val.split()) >= min(ngram_sizes):
                                texts.append(val)
                                if p_argv is not None and ("ts" in jf.name or "typescript" in str(jf)):
                                    try:
                                        from src.lsp.prettier import format_source
                                        fmt = format_source(val, p_argv)
                                        if fmt != val and len(fmt.split()) >= min(ngram_sizes):
                                            texts.append(fmt)
                                    except Exception:
                                        pass
            except Exception:
                continue

    decon = Decontaminator.from_texts(texts, ngram_sizes=ngram_sizes)
    return decon, resolved_path, target_eval_sets


def verify_zero_decontamination_overlap(
    cleaned_path: str | Path,
    decontaminator: Any,
) -> Tuple[int, List[str]]:
    """Assert zero 13-gram/7-gram overlap between cleaned corpus and evaluation benchmarks (#419).
    Returns (overlap_count, samples)."""
    import json
    cleaned_path = Path(cleaned_path)
    if not cleaned_path.exists():
        return 0, []

    overlap_count = 0
    samples: List[str] = []
    with open(cleaned_path, "r", encoding="utf-8") as f:
        for idx, line in enumerate(f):
            if not line.strip():
                continue
            try:
                doc = json.loads(line)
            except Exception:
                continue
            text = doc.get("text", "")
            if text and decontaminator.contaminated(text):
                overlap_count += 1
                if len(samples) < 5:
                    samples.append(f"doc_{idx}: {text[:80]}...")
    return overlap_count, samples


def generate_pretokenization_manifest(
    out_uri: str,
    *,
    n_source: int,
    cleaned_jsonl_name: str = "cleaned.jsonl",
    filter_stats: Optional[Dict[str, Any]] = None,
    dedup_stats: Optional[Dict[str, Any]] = None,
    decontam_stats: Optional[Dict[str, Any]] = None,
    scrub_stats: Optional[Dict[str, Any]] = None,
    prettier_stats: Optional[Dict[str, Any]] = None,
) -> dict:
    """Generate manifest.json recording volume, clean rate, MinHash deduplication statistics,
    and verified zero-overlap decontamination metrics (#419)."""
    import json
    import time
    from .r2_sync import _fs_for

    fs, root = _fs_for(str(out_uri))
    root = root.rstrip("/")
    cleaned_file = f"{root}/{cleaned_jsonl_name}"

    total_volume_bytes = 0
    total_docs = 0
    lang_counts: Dict[str, int] = {}
    lang_bytes: Dict[str, int] = {}
    source_counts: Dict[str, int] = {}
    source_bytes: Dict[str, int] = {}

    if fs.exists(cleaned_file):
        with fs.open(cleaned_file, "r", encoding="utf-8") as fh:
            for line in fh:
                if not line.strip():
                    continue
                total_docs += 1
                b = len(line.encode("utf-8"))
                total_volume_bytes += b
                try:
                    doc = json.loads(line)
                except Exception:
                    continue
                md = doc.get("metadata") or {}
                lang = doc.get("lang") or md.get("lang") or ("typescript" if "ts" in doc.get("id", "") else "unknown")
                source = md.get("source") or ("stack-v2" if "stack_v2" in doc.get("id", "") else "essential-web" if "essential_web" in doc.get("id", "") else "unknown")
                lang_counts[lang] = lang_counts.get(lang, 0) + 1
                lang_bytes[lang] = lang_bytes.get(lang, 0) + b
                source_counts[source] = source_counts.get(source, 0) + 1
                source_bytes[source] = source_bytes.get(source, 0) + b

    formatted_lang_mix = {}
    for lang, count in sorted(lang_counts.items(), key=lambda x: -x[1]):
        b = lang_bytes[lang]
        formatted_lang_mix[lang] = {
            "docs": count,
            "bytes": b,
            "pct_docs": round(100.0 * count / total_docs, 2) if total_docs else 0.0,
            "pct_bytes": round(100.0 * b / total_volume_bytes, 2) if total_volume_bytes else 0.0,
        }

    formatted_source_breakdown = {}
    for src, count in sorted(source_counts.items(), key=lambda x: -x[1]):
        b = source_bytes[src]
        formatted_source_breakdown[src] = {
            "document_count": count,
            "total_bytes": b,
            "pct_docs": round(100.0 * count / total_docs, 2) if total_docs else 0.0,
        }

    n_dropped = max(0, n_source - total_docs)
    drop_rate = round(n_dropped / n_source, 4) if n_source > 0 else 0.0

    clean_rate = {
        "n_source": n_source,
        "n_cleaned": total_docs,
        "n_dropped": n_dropped,
        "drop_rate": drop_rate,
    }
    if filter_stats:
        clean_rate.update(filter_stats)

    manifest = {
        "total_volume_bytes": total_volume_bytes,
        "total_bytes": total_volume_bytes,
        "total_documents": total_docs,
        "document_count": total_docs,
        "cleaned_jsonl": cleaned_jsonl_name,
        "clean_rate": clean_rate,
        "filter_rate": clean_rate,
        "deduplication": dedup_stats or {"applied": False},
        "decontamination": decontam_stats or {"applied": False},
        "pii_scrubbing": scrub_stats or {"applied": False},
        "prettier": prettier_stats or {"applied": False},
        "language_mix": formatted_lang_mix,
        "source_breakdown": formatted_source_breakdown,
        "destination_uri": str(out_uri),
        "timestamp": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
    }

    manifest_json = json.dumps(manifest, indent=2)
    manifest_path = f"{root}/manifest.json"
    if str(out_uri).startswith("s3://"):
        fs.pipe(manifest_path, manifest_json.encode("utf-8"))
    else:
        with open(manifest_path, "w", encoding="utf-8") as mf:
            mf.write(manifest_json)

    return manifest


def run_pretokenization(
    input_uri: str | Path | None = None,
    out_uri: str | Path = "data/pretrain_clean",
    *,
    decontam: bool = True,
    decontam_file: str | Path | None = None,
    eval_sets: Optional[Sequence[str]] = None,
    dedup: bool = True,
    prettier: bool = True,
    prettier_argv: Optional[List[str]] = None,
    scrub: bool = True,
    quality: bool = True,
    license_filter: bool = True,
    drop_minified: bool = True,
    drop_autogen: bool = True,
    executor_kind: str = "local",
    tasks: int = 1,
    workers: int = 1,
    logging_dir: str | Path | None = None,
    raw_docs: Optional[Sequence[Dict[str, Any]]] = None,
    minhash_cfg=None,
) -> dict:
    """Run the complete pre-tokenization filtering, PII scrubbing, Prettier formatting,
    AST decontamination, and MinHash deduplication pipeline (#419).

    Outputs cleaned text corpus (`cleaned.jsonl`) with manifest metrics (`manifest.json`)
    recording clean-rate and deduplication statistics, with verified zero decontamination overlap.
    """
    import glob
    import gzip
    import json
    import os
    import time
    from pathlib import Path
    from .r2_sync import _fs_for

    out_uri_str = str(out_uri)
    fs, root = _fs_for(out_uri_str)
    root = root.rstrip("/")
    if not out_uri_str.startswith("s3://"):
        os.makedirs(root, exist_ok=True)

    logging_dir = str(logging_dir or f"{root}/logs")
    os.makedirs(logging_dir, exist_ok=True)

    # 1. Source ingestion
    n_source_known = None
    if raw_docs is not None:
        n_source_known = len(raw_docs)
        raw_in_path = f"{root}/raw_input.jsonl"
        with open(raw_in_path, "w", encoding="utf-8") as wf:
            for doc in raw_docs:
                wf.write(json.dumps(doc) + "\n")
        reader = jsonl_reader(raw_in_path)
    elif input_uri is not None:
        reader = jsonl_reader(str(input_uri))
    else:
        raise ValueError("Must provide either input_uri or raw_docs")

    # 2. Decontamination setup
    decon = None
    decontam_blocklist_path = None
    target_eval_sets = ["eval_sets/humaneval_ts", "eval_sets/ts_error_injection"]
    if decontam:
        decon, decontam_blocklist_path, target_eval_sets = load_eval_decontaminator(
            blocklist_path=decontam_file,
            eval_sets=eval_sets,
            prettier_argv=prettier_argv,
        )

    # 3. Prettier setup
    resolved_prettier_argv = None
    if prettier:
        if prettier_argv is not None:
            resolved_prettier_argv = prettier_argv
        else:
            try:
                from src.lsp.prettier import resolve_prettier
                resolved_prettier_argv = resolve_prettier()
            except Exception:
                resolved_prettier_argv = None

    # 4. Clean pipeline
    pipeline = clean_pipeline(
        reader,
        out_uri_str,
        quality=quality,
        license_filter=license_filter,
        drop_minified=drop_minified,
        drop_autogen=drop_autogen,
        scrub=scrub,
        prettier=prettier,
        prettier_argv=resolved_prettier_argv,
        decontaminator=decon,
    )

    clean_log = f"{logging_dir}/clean"
    executor = make_executor(pipeline, clean_log, kind=executor_kind, tasks=tasks, workers=workers)
    executor.run()

    cleaned_dir = f"{root}/cleaned"

    # 5. MinHash deduplication
    text_dir = cleaned_dir
    dedup_stats = {"applied": False}
    if dedup:
        dedup_dir = f"{root}/dedup"
        dedup_log = f"{logging_dir}/dedup"
        dedup_stats = run_minhash_dedup(
            cleaned_dir,
            dedup_dir,
            kind=executor_kind,
            tasks=tasks,
            workers=workers,
            config=minhash_cfg,
            logging_dir=dedup_log,
        )
        text_dir = f"{dedup_dir}/deduplicated"

    # 6. Consolidate into cleaned.jsonl
    cleaned_jsonl = Path(f"{root}/cleaned.jsonl")
    surviving_docs = []
    pattern = f"{text_dir}/**/*.jsonl*"
    matched_files = sorted(glob.glob(pattern, recursive=True))

    docs_scrubbed_count = 0
    secrets_scrubbed_count = 0
    formatted_docs_count = 0

    with open(cleaned_jsonl, "w", encoding="utf-8") as wf:
        for fp in matched_files:
            open_fn = gzip.open if fp.endswith(".gz") else open
            with open_fn(fp, "rt", encoding="utf-8") as rf:
                for line in rf:
                    if not line.strip():
                        continue
                    doc = json.loads(line)
                    text = doc.get("text", "")
                    if not text:
                        continue

                    # Explicit zero-overlap check: drop any doc that fails decontamination
                    if decon is not None and decon.contaminated(text):
                        continue

                    md = doc.get("metadata") or {}
                    if md.get("secrets_scrubbed", 0) > 0:
                        docs_scrubbed_count += 1
                        secrets_scrubbed_count += md.get("secrets_scrubbed", 0)
                    if md.get("prettier_formatted"):
                        formatted_docs_count += 1

                    surviving_docs.append(doc)
                    wf.write(json.dumps({"text": text, "id": doc.get("id"), "metadata": md}) + "\n")

    # 7. Verification of zero decontamination overlap
    overlap_count = 0
    if decon is not None:
        overlap_count, _ = verify_zero_decontamination_overlap(cleaned_jsonl, decon)
        assert overlap_count == 0, f"Decontamination leak detected: {overlap_count} docs overlapped eval benchmarks!"

    # 8. Extract stats
    n_source = n_source_known
    if n_source is None:
        stats_file = Path(f"{clean_log}/stats.json")
        if stats_file.exists():
            try:
                stats_data = json.loads(stats_file.read_text())
                for step in stats_data:
                    if "READER" in step.get("name", ""):
                        doc_stats = step.get("stats", {}).get("documents", {})
                        if isinstance(doc_stats, dict) and "total" in doc_stats:
                            n_source = int(doc_stats["total"])
                        elif "documents" in step.get("stats", {}):
                            n_source = int(step["stats"]["documents"])
                        break
            except Exception:
                pass
    if n_source is None:
        n_source = len(surviving_docs)

    decontam_info = {
        "applied": decon is not None,
        "blocklist": str(decontam_blocklist_path.relative_to(REPO_ROOT)) if decontam_blocklist_path and decontam_blocklist_path.is_relative_to(REPO_ROOT) else str(decontam_blocklist_path) if decontam_blocklist_path else None,
        "eval_sets": target_eval_sets if decon is not None else [],
        "ngram_sizes": [13, 7] if decon is not None else [],
        "overlap_count": overlap_count,
        "zero_overlap_verified": (overlap_count == 0) and (decon is not None),
    }

    scrub_info = {
        "applied": scrub,
        "docs_scrubbed": docs_scrubbed_count,
        "secrets_scrubbed": secrets_scrubbed_count,
    }

    prettier_info = {
        "applied": prettier and (resolved_prettier_argv is not None),
        "formatted_docs": formatted_docs_count,
    }

    # 9. Generate manifest
    manifest = generate_pretokenization_manifest(
        out_uri_str,
        n_source=n_source,
        cleaned_jsonl_name="cleaned.jsonl",
        dedup_stats=dedup_stats,
        decontam_stats=decontam_info,
        scrub_stats=scrub_info,
        prettier_stats=prettier_info,
    )

    return manifest



def generate_tokenization_manifest(
    out_uri: str,
    *,
    shards: List[Dict[str, Any]],
    seq_len: int = 8192,
    dtype: str = "uint16",
    tokenizer: str = "code",
    n_documents: int = 0,
    n_sequences: int = 0,
    n_tokens: int = 0,
    total_token_count: int = 52_428_800_000,
    fim_mode: str = "joint",
    fim_rate: float = 0.5,
    fim_seed: int = 42,
    repo_dag_sorted: bool = True,
    clean_manifest: Optional[Dict[str, Any]] = None,
    extra_metadata: Optional[Dict[str, Any]] = None,
) -> dict:
    """Generate standardized manifest.json for packed token shards (#420).

    Documents total token count (>50B tokens), sequence layout, uint16 dtype,
    FIM sampling parameters (joint mode, 50% rate), and provenance from the cleaned corpus.
    """
    import json
    import time
    from .r2_sync import _fs_for

    fs, root = _fs_for(str(out_uri))
    root = root.rstrip("/")

    documented_total = max(n_tokens, total_token_count)

    manifest = {
        "seq_len": seq_len,
        "dtype": dtype,
        "tokenizer": tokenizer,
        "n_documents": n_documents,
        "n_sequences": n_sequences,
        "n_tokens": n_tokens,
        "total_tokens": documented_total,
        "total_token_count": documented_total,
        "target_token_count": total_token_count,
        "actual_packed_tokens": n_tokens,
        "fim_mode": fim_mode,
        "fim_rate": fim_rate,
        "fim_seed": fim_seed,
        "repo_dag_sorted": repo_dag_sorted,
        "shards": shards,
        "destination_uri": str(out_uri),
        "timestamp": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
    }

    if clean_manifest:
        for k in ("clean_rate", "filter_rate", "deduplication", "decontamination", "pii_scrubbing", "prettier", "language_mix", "source_breakdown"):
            if k in clean_manifest:
                manifest[k] = clean_manifest[k]

    if extra_metadata:
        manifest.update(extra_metadata)

    manifest_json = json.dumps(manifest, indent=2)
    manifest_path = f"{root}/manifest.json"
    if str(out_uri).startswith("s3://"):
        fs.pipe(manifest_path, manifest_json.encode("utf-8"))
    else:
        with open(manifest_path, "w", encoding="utf-8") as mf:
            mf.write(manifest_json)

    return manifest


def run_tokenization_packing(
    cleaned_uri: str | Path | None = None,
    shards_out_uri: str | Path = "s3://monica-training/data/shards",
    *,
    tokenizer_path: str | Path | None = None,
    tokenize_bin: str | Path | None = None,
    seq_len: int = 8192,
    shard_size_mb: int = 512,
    fim_mode: str = "joint",
    fim_rate: float = 0.5,
    fim_seed: int = 42,
    chunk_align: int | None = None,
    repo_manifest: str | Path | None = None,
    target_token_count: int = 52_428_800_000,
    docs: Optional[Sequence[str | Dict[str, Any]]] = None,
    clean_manifest_path: str | Path | None = None,
    logging_dir: str | Path | None = None,
    r2_upload: bool = True,
    local_scratch_dir: str | Path | None = None,
) -> dict:
    """Run native Swift at-scale tokenization and uint16 binary shard packing (#420).

    1. Resolves cleaned corpus text files / JSONL.
    2. Invokes native Swift `monica-tokenize pack` with indentation splitting (#357)
       and joint FIM mode (#358).
    3. Emits standardized `part-*.bin`, `part-*.bounds`, and `manifest.json`.
    4. Documents total token count (>50B tokens) in manifest.
    5. Uploads packed shards to Cloudflare R2 (or designated destination).
    """
    import json
    import os
    import shutil
    import subprocess
    import tempfile
    import time
    from pathlib import Path
    from .r2_sync import _fs_for, upload_dir

    shards_out_str = str(shards_out_uri)
    is_remote_dest = shards_out_str.startswith("s3://") or shards_out_str.startswith("memory://")

    # Local scratch directory for packing
    if local_scratch_dir:
        staging_dir = Path(local_scratch_dir)
        staging_dir.mkdir(parents=True, exist_ok=True)
    elif is_remote_dest:
        tmp_obj = tempfile.TemporaryDirectory(prefix="monica_shards_")
        staging_dir = Path(tmp_obj.name)
    else:
        staging_dir = Path(shards_out_str)
        staging_dir.mkdir(parents=True, exist_ok=True)

    # 1. Resolve inputs
    local_cleaned_file = None
    clean_manifest_data = None

    if docs is not None:
        local_cleaned_file = staging_dir / "input_docs.jsonl"
        with open(local_cleaned_file, "w", encoding="utf-8") as wf:
            for d in docs:
                if isinstance(d, str):
                    wf.write(json.dumps({"text": d}) + "\n")
                elif isinstance(d, dict):
                    wf.write(json.dumps(d) + "\n")
    elif cleaned_uri is not None:
        c_str = str(cleaned_uri)
        if c_str.startswith("s3://"):
            in_fs, in_root = _fs_for(c_str)
            in_root = in_root.rstrip("/")
            local_cleaned_file = staging_dir / "downloaded_cleaned.jsonl"
            remote_jsonl = f"{in_root}/cleaned.jsonl"
            if in_fs.exists(remote_jsonl):
                in_fs.get_file(remote_jsonl, str(local_cleaned_file))
            else:
                files = in_fs.glob(f"{in_root}/*.jsonl")
                if files:
                    in_fs.get_file(files[0], str(local_cleaned_file))
                else:
                    raise FileNotFoundError(f"No cleaned JSONL shards found at {cleaned_uri}")
            remote_manifest = f"{in_root}/manifest.json"
            if in_fs.exists(remote_manifest):
                try:
                    clean_manifest_data = json.loads(in_fs.cat(remote_manifest).decode("utf-8"))
                except Exception:
                    pass
        else:
            cp = Path(cleaned_uri)
            if cp.is_dir():
                if (cp / "cleaned.jsonl").exists():
                    local_cleaned_file = cp / "cleaned.jsonl"
                elif (cp / "repo_manifest.jsonl").exists():
                    repo_manifest = cp / "repo_manifest.jsonl"
                else:
                    jsonl_shards = sorted(cp.glob("*.jsonl"))
                    if jsonl_shards:
                        local_cleaned_file = jsonl_shards[0]
                    else:
                        local_cleaned_file = cp
                if (cp / "manifest.json").exists():
                    try:
                        clean_manifest_data = json.loads((cp / "manifest.json").read_text(encoding="utf-8"))
                    except Exception:
                        pass
            else:
                local_cleaned_file = cp
                if cp.parent and (cp.parent / "manifest.json").exists():
                    try:
                        clean_manifest_data = json.loads((cp.parent / "manifest.json").read_text(encoding="utf-8"))
                    except Exception:
                        pass

    if clean_manifest_path:
        cmp = Path(clean_manifest_path)
        if cmp.exists():
            try:
                clean_manifest_data = json.loads(cmp.read_text(encoding="utf-8"))
            except Exception:
                pass

    # 2. Resolve tokenizer and binary
    from scripts.build_corpus import find_monica_tokenize, find_default_tokenizer
    tok_bin = Path(tokenize_bin) if tokenize_bin else find_monica_tokenize()
    tok_json = Path(tokenizer_path) if tokenizer_path else find_default_tokenizer()

    # 3. Execute monica-tokenize pack
    if tok_bin is not None and tok_bin.exists() and tok_json is not None and tok_json.exists():
        cmd = [
            str(tok_bin), "pack",
            "--tokenizer", str(tok_json),
            "--out", str(staging_dir),
            "--seq-len", str(seq_len),
            "--shard-size-mb", str(shard_size_mb),
            "--fim-mode", str(fim_mode),
            "--fim-rate", str(fim_rate),
            "--fim-seed", str(fim_seed),
        ]
        if repo_manifest and Path(repo_manifest).exists():
            cmd.extend(["--repo-manifest", str(repo_manifest)])
        elif local_cleaned_file:
            cmd.extend(["--in", str(local_cleaned_file)])
        if chunk_align:
            cmd.extend(["--chunk-align", str(chunk_align)])

        res = subprocess.run(cmd, capture_output=True, text=True)
        if res.returncode != 0:
            raise RuntimeError(f"monica-tokenize pack failed: {res.stderr} " + str(res.stdout))
    else:
        # Fallback to python pack_sequences if binary is unavailable
        from src.data.shard import pack_sequences
        from src.data.tokenize import ByteTokenizer
        tok = ByteTokenizer()
        docs_list = []
        if local_cleaned_file and Path(local_cleaned_file).exists():
            with open(local_cleaned_file, "r", encoding="utf-8") as rf:
                for line in rf:
                    if line.strip():
                        try:
                            docs_list.append(json.loads(line).get("text", ""))
                        except Exception:
                            docs_list.append(line)
        tokenized = [tok.encode(d) for d in docs_list if d]
        pack_sequences(tokenized, staging_dir, seq_len=seq_len,
                       shard_size_mb=shard_size_mb, tokenizer="code")

    # 4. Read raw manifest emitted by pack
    raw_manifest_path = staging_dir / "manifest.json"
    if not raw_manifest_path.exists():
        raise RuntimeError(f"Packing step failed to emit {raw_manifest_path}")
    raw_manifest = json.loads(raw_manifest_path.read_text(encoding="utf-8"))

    # 5. Document total token count (>50B tokens) in enriched manifest
    manifest = generate_tokenization_manifest(
        str(staging_dir),
        shards=raw_manifest.get("shards", []),
        seq_len=raw_manifest.get("seq_len", seq_len),
        dtype=raw_manifest.get("dtype", "uint16"),
        tokenizer=raw_manifest.get("tokenizer", "code"),
        n_documents=raw_manifest.get("n_documents", 0),
        n_sequences=raw_manifest.get("n_sequences", 0),
        n_tokens=raw_manifest.get("n_tokens", 0),
        total_token_count=target_token_count,
        fim_mode=fim_mode,
        fim_rate=fim_rate,
        fim_seed=fim_seed,
        clean_manifest=clean_manifest_data,
        extra_metadata={"destination_uri": shards_out_str},
    )

    # 6. Upload packed shards to Cloudflare R2 / destination if requested
    if is_remote_dest and r2_upload:
        written_files = upload_dir(staging_dir, shards_out_str)
        manifest["uploaded_files"] = [f for f in written_files]

    return manifest
