"""Scale corpus pipeline on HF datatrove (#80) — the pod/cluster port of the laptop-scale
`src/data/` stages.

The offline stages (`corpus.py` / `filters.py` / `dedup.py`) are "the laptop-scale version of
the datatrove pipeline" (docs/design/08-corpus-pipeline.md): same common schema
`{text, source, lang, license, meta}`, same six-stage shape. This module is the **port onto
datatrove** so the full-source build (FineWeb-Edu + supplements, cross-source MinHash) runs on a
CPU pod, while **reusing** the project filter/dedup *logic* rather than re-deriving it:

    HuggingFaceDatasetReader        ingest (FineWeb-Edu first; sources are config-driven)
      -> LicenseFilter              filters.license_ok          (permissive-only on code)
      -> QualityFilter              filters.text_quality_ok     (FineWeb/Gopher-style heuristics)
      -> MinifiedAutogenFilter      filters.looks_minified / looks_autogenerated
      -> DecontaminationFilter      dedup.Decontaminator        (13/7-gram benchmark overlap)
      -> SecretScrubber             filters.scrub_secrets       (mapper: redacts secrets/PII)
      -> JsonlWriter                cleaned text shards under <out>/cleaned
    [then] datatrove-native MinHash dedup (the distributed win) -> <out>/dedup

The datatrove/our-code boundary stops at **cleaned text**: the existing `tokenize.py`/`pack.py`/
`shard.py` turn cleaned shards into the Qwen2.5 uint32 trainer shards (trainer format unchanged).

ABOVE THE SEAM — datatrove has **no torch dependency**, and every datatrove import here is **lazy**
(inside functions / a block factory) so the module imports cleanly on the main py3.14 env where
datatrove isn't installed (the seam guard imports it there). datatrove runs in the dedicated py3.11
venv (`.venv-dt`) that matches the RunPod images; `tests/test_datatrove_pipeline.py` skips where it
is absent.
"""

from __future__ import annotations

from typing import List, Optional

from . import storage
from .corpus import Record
from .filters import (DEFAULT_THRESHOLDS, QualityThresholds, license_ok, looks_autogenerated,
                      looks_minified, scrub_secrets, text_quality_ok)

#: FineWeb-Edu on the Hub (curated web-text spine, ODC-BY) — the first concrete source (#70).
FINEWEB_EDU_DATASET = "HuggingFaceFW/fineweb-edu"


def to_record(doc) -> Record:
    """A `filters`/`dedup` Record view of a datatrove Document (schema lives in `doc.metadata`)."""
    md = doc.metadata or {}
    return Record(text=doc.text, source=md.get("source", ""), lang=md.get("lang", "en"),
                  license=md.get("license", "unknown"), meta=md)


def _folder(uri):
    """A datatrove output_folder spec for an fsspec URI. For `s3://` inject the R2 endpoint from the
    env (key/secret come from `AWS_*` via s3fs); local paths pass through unchanged."""
    if str(uri).startswith("s3://"):
        from .r2_sync import r2_endpoint
        endpoint = r2_endpoint()
        if endpoint:
            return (str(uri), {"client_kwargs": {"endpoint_url": endpoint}})
    return str(uri)


def _custom_blocks(thresholds: QualityThresholds = DEFAULT_THRESHOLDS):
    """Define the project's filter/scrub blocks as datatrove steps (lazy import). Returns a dict of
    the block classes so `clean_pipeline` can instantiate the enabled ones."""
    from datatrove.pipeline.base import PipelineStep
    from datatrove.pipeline.filters.base_filter import BaseFilter

    class LicenseFilter(BaseFilter):
        """Keep text always; keep code only under a permissive / flagged-share-alike license."""
        name = "🔑 license"

        def filter(self, doc):
            return license_ok(to_record(doc))

    class QualityFilter(BaseFilter):
        """Drop gross-junk TEXT (curated code passes); reuses `filters.text_quality_ok`."""
        name = "✨ quality"

        def filter(self, doc):
            rec = to_record(doc)
            from .filters import is_code_record
            if is_code_record(rec):
                return True
            return text_quality_ok(doc.text, thresholds)

    class MinifiedAutogenFilter(BaseFilter):
        """Drop minified / autogenerated CODE."""
        name = "🧹 minified/autogen"

        def filter(self, doc):
            rec = to_record(doc)
            from .filters import is_code_record
            if not is_code_record(rec):
                return True
            return not (looks_minified(doc.text) or looks_autogenerated(doc.text))

    class DecontaminationFilter(BaseFilter):
        """Drop docs whose 13/7-gram windows overlap the eval benchmarks (`dedup.Decontaminator`)."""
        name = "🧴 decontaminate"

        def __init__(self, decontaminator, **kw):
            super().__init__(**kw)
            self._decon = decontaminator

        def filter(self, doc):
            return not self._decon.contaminated(doc.text)

    class SecretScrubber(PipelineStep):
        """Mapper: redact secrets/PII in place (`filters.scrub_secrets`), tag count in metadata."""
        name = "🔒 scrub"

        def run(self, data, rank: int = 0, world_size: int = 1):
            for doc in data:
                scrubbed, n = scrub_secrets(doc.text)
                if n:
                    doc.text = scrubbed
                    doc.metadata["secrets_scrubbed"] = doc.metadata.get("secrets_scrubbed", 0) + n
                    self.stat_update("docs_scrubbed")
                    self.stat_update("secrets_scrubbed", value=n)
                yield doc

    return {"LicenseFilter": LicenseFilter, "QualityFilter": QualityFilter,
            "MinifiedAutogenFilter": MinifiedAutogenFilter,
            "DecontaminationFilter": DecontaminationFilter, "SecretScrubber": SecretScrubber}


def fineweb_edu_reader(*, limit: int = -1, streaming: bool = True, split: str = "train"):
    """A datatrove reader over FineWeb-Edu, tagged with the common-schema source/lang/license so the
    downstream filters key on it identically to the local path. `limit<0` means no cap."""
    from datatrove.pipeline.readers import HuggingFaceDatasetReader
    return HuggingFaceDatasetReader(
        dataset=FINEWEB_EDU_DATASET,
        dataset_options={"split": split},
        streaming=streaming,
        limit=limit,
        text_key="text",
        id_key="id",
        default_metadata={"source": "fineweb-edu", "lang": "en", "license": "odc-by"},
    )


def clean_pipeline(reader, out_uri, *, quality: bool = False, license_filter: bool = False,
                   drop_minified: bool = False, drop_autogen: bool = False, scrub: bool = False,
                   decontaminator=None, thresholds: QualityThresholds = DEFAULT_THRESHOLDS,
                   output_filename: str = "${rank}.jsonl.gz") -> list:
    """Stages 2–5 as a datatrove pipeline: reader -> enabled filters/scrub -> cleaned JSONL shards
    under `<out_uri>/cleaned`. `out_uri` is a `storage.py` class root (`file://` local,
    `s3://monica-training/...` on a pod). Filters are opt-in, mirroring `corpus.build_corpus`."""
    from datatrove.pipeline.writers import JsonlWriter

    blocks = _custom_blocks(thresholds)
    steps: list = [reader]
    if license_filter:
        steps.append(blocks["LicenseFilter"]())
    if quality:
        steps.append(blocks["QualityFilter"]())
    if drop_minified or drop_autogen:
        steps.append(blocks["MinifiedAutogenFilter"]())
    if decontaminator is not None:
        steps.append(blocks["DecontaminationFilter"](decontaminator))
    if scrub:
        steps.append(blocks["SecretScrubber"]())
    cleaned_dir = f"{str(out_uri).rstrip('/')}/cleaned"
    steps.append(JsonlWriter(output_folder=_folder(cleaned_dir), output_filename=output_filename))
    return steps


def make_executor(pipeline: list, logging_dir, *, kind: str = "local", tasks: int = 1,
                  workers: int = 1, depends=None, **slurm_kwargs):
    """Wrap a pipeline in an executor. `kind="local"` -> LocalPipelineExecutor (Mac / single pod);
    `kind="slurm"` -> SlurmPipelineExecutor (cluster). `depends` chains multi-stage runs."""
    if kind == "local":
        from datatrove.executor import LocalPipelineExecutor
        return LocalPipelineExecutor(pipeline=pipeline, logging_dir=str(logging_dir),
                                     tasks=tasks, workers=workers, depends=depends)
    if kind == "slurm":
        from datatrove.executor import SlurmPipelineExecutor
        return SlurmPipelineExecutor(pipeline=pipeline, logging_dir=str(logging_dir),
                                     tasks=tasks, depends=depends, **slurm_kwargs)
    raise ValueError(f"unknown executor kind {kind!r} (use 'local' or 'slurm')")


def minhash_config(*, num_buckets: int = 14, hashes_per_bucket: int = 8, precision: int = 64):
    """datatrove MinhashConfig (the LSH banding that sizes the dedup)."""
    from datatrove.pipeline.dedup.minhash import MinhashConfig
    from datatrove.utils.hashing import HashConfig
    return MinhashConfig(hash_config=HashConfig(precision=precision),
                         num_buckets=num_buckets, hashes_per_bucket=hashes_per_bucket)


def run_minhash_dedup(cleaned_uri, base_uri, *, kind: str = "local", tasks: int = 1,
                      workers: int = 1, config=None, logging_dir=None) -> None:
    """The standard datatrove 4-stage cross-source MinHash dedup, run end to end over the cleaned
    JSONL at `cleaned_uri`. Intermediates + the deduplicated output live under `base_uri`:
    `signatures/ buckets/ remove_ids/ deduplicated/`. Each stage `depends=` the previous one."""
    from datatrove.pipeline.dedup import (MinhashDedupBuckets, MinhashDedupCluster,
                                          MinhashDedupFilter, MinhashDedupSignature)
    from datatrove.pipeline.readers import JsonlReader
    from datatrove.pipeline.writers import JsonlWriter

    cfg = config or minhash_config()
    base = str(base_uri).rstrip("/")
    logging_dir = str(logging_dir or f"{base}/logs")
    sig, buckets, ids, out = (f"{base}/signatures", f"{base}/buckets",
                              f"{base}/remove_ids", f"{base}/deduplicated")

    # datatrove's fixed stage-task topology: signatures + filter run one task per input shard;
    # buckets MUST run exactly num_buckets tasks (it shards by bucket); clustering is single-task.
    s1 = make_executor([JsonlReader(_folder(cleaned_uri)),
                        MinhashDedupSignature(output_folder=_folder(sig), config=cfg)],
                       f"{logging_dir}/sig", kind=kind, tasks=tasks, workers=workers)
    s2 = make_executor([MinhashDedupBuckets(input_folder=_folder(sig),
                                            output_folder=_folder(buckets), config=cfg)],
                       f"{logging_dir}/buckets", kind=kind, tasks=cfg.num_buckets,
                       workers=workers, depends=s1)
    s3 = make_executor([MinhashDedupCluster(input_folder=_folder(buckets),
                                            output_folder=_folder(ids), config=cfg)],
                       f"{logging_dir}/cluster", kind=kind, tasks=1, workers=1, depends=s2)
    s4 = make_executor([JsonlReader(_folder(cleaned_uri)),
                        MinhashDedupFilter(input_folder=_folder(ids),
                                           exclusion_writer=JsonlWriter(_folder(f"{base}/removed"))),
                        JsonlWriter(output_folder=_folder(out))],
                       f"{logging_dir}/filter", kind=kind, tasks=tasks, workers=workers, depends=s3)
    s4.run()
