"""Stage-3 quality + license filters (#72).

The corpus skeleton (#69) shipped a placeholder ``filter_records`` that only checked a
length floor. This module is the real Stage-3 from
``docs/design/08-corpus-pipeline.md`` (line 52): light heuristics on text, **permissive-
license-only** gating on code, dropping autogenerated/minified files, and scrubbing
secrets/PII. Every filter keys on the common schema ``Record{text, source, lang, license,
meta}`` so all sources are treated identically.

ABOVE THE SEAM — pure Python stdlib (``re``/``math``), no ``mlx``/``torch`` and no heavy
data deps. ``corpus.filter_records`` delegates here; the filters are **opt-in** (default
off) so the #69 local-gate path is byte-for-byte unchanged — real runs turn them on via
``build_corpus(..., quality=True, scrub=True, license_filter=True)`` or the CLI flags.

At scale (#80) these map onto ``datatrove`` filter stages keyed on the same schema fields.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Iterable, Iterator, List, Optional, Tuple

from .corpus import Record

# --------------------------------------------------------------------------- #
# License gating (code only — text licenses are tracked, not excluded)
# --------------------------------------------------------------------------- #
#: Permissive licenses we keep for CODE outright.
PERMISSIVE_LICENSES = frozenset({
    "mit", "apache-2.0", "apache2.0", "apache 2.0", "apache",
    "bsd", "bsd-2-clause", "bsd-3-clause", "isc", "unlicense", "0bsd",
    "odc-by", "cc0-1.0", "cc0", "wtfpl", "zlib", "mpl-2.0",
})
#: Share-alike / attribution licenses — kept but FLAGGED (attribution + share-alike
#: obligations carried in the blend accounting, per the design doc).
FLAGGED_LICENSES = frozenset({
    "cc-by-sa", "cc-by-sa-3.0", "cc-by-sa-4.0", "cc-by", "cc-by-4.0", "cc-by-3.0",
})

#: Languages we treat as CODE (the permissive-only gate applies to these).
CODE_LANGS = frozenset({
    "python", "javascript", "typescript", "java", "c", "cpp", "c++", "csharp", "c#",
    "go", "rust", "ruby", "php", "sql", "shell", "bash", "html", "css", "scala",
    "kotlin", "swift", "r", "matlab", "perl", "lua", "haskell", "objective-c", "dart",
})


def normalize_license(license: str) -> str:
    """Lowercase + trim a license string for set membership."""
    return (license or "").strip().lower()


def is_permissive(license: str) -> bool:
    return normalize_license(license) in PERMISSIVE_LICENSES


def is_flagged(license: str) -> bool:
    """Share-alike / attribution — kept but obligation-bearing."""
    return normalize_license(license) in FLAGGED_LICENSES


def is_code_record(record: Record) -> bool:
    """Code if the schema says so: ``meta.is_code``/``meta.content_type==code`` first,
    then the language, then a code-ish source name (e.g. ``the-stack``)."""
    meta = record.meta or {}
    if meta.get("is_code") is True or meta.get("content_type") == "code":
        return True
    if (record.lang or "").strip().lower() in CODE_LANGS:
        return True
    src = (record.source or "").lower()
    return "stack" in src or "code" in src or "github" in src


def license_ok(record: Record) -> bool:
    """Keep decision by license. **Code** must be permissive (or flagged share-alike);
    **text** is always license-OK (its obligations are tracked, not excluded)."""
    if not is_code_record(record):
        return True
    lic = normalize_license(record.license)
    return lic in PERMISSIVE_LICENSES or lic in FLAGGED_LICENSES


# --------------------------------------------------------------------------- #
# Text quality heuristics (FineWeb-Edu / Gopher style, light)
# --------------------------------------------------------------------------- #
@dataclass
class QualityThresholds:
    """Light text-quality bounds. Curated sources already did the heavy lifting, so
    these only catch gross junk (boilerplate, symbol soup, single tokens)."""

    min_chars: int = 200
    min_words: int = 10
    min_mean_word_len: float = 2.0
    max_mean_word_len: float = 12.0
    min_alpha_ratio: float = 0.5          # fraction of chars that are letters
    max_symbol_ratio: float = 0.30        # non-alphanumeric, non-space
    max_digit_ratio: float = 0.30
    max_top_word_ratio: float = 0.50      # most-common word as fraction of all words
    repetition_min_words: int = 20        # only judge repetition on docs this long


DEFAULT_THRESHOLDS = QualityThresholds()

_WORD_RE = re.compile(r"\S+")


def text_quality_reasons(text: str, th: QualityThresholds = DEFAULT_THRESHOLDS) -> List[str]:
    """Return the list of failed checks (empty list == passes). Useful for tests/debug."""
    reasons: List[str] = []
    s = text.strip()
    n = len(s)
    if n < th.min_chars:
        reasons.append("too_short")
    words = _WORD_RE.findall(s)
    if len(words) < th.min_words:
        reasons.append("too_few_words")
    if n == 0:
        return reasons  # nothing more to measure

    mean_wl = (sum(len(w) for w in words) / len(words)) if words else 0.0
    if words and not (th.min_mean_word_len <= mean_wl <= th.max_mean_word_len):
        reasons.append("mean_word_len")

    alpha = sum(c.isalpha() for c in s)
    digit = sum(c.isdigit() for c in s)
    symbol = sum((not c.isalnum()) and (not c.isspace()) for c in s)
    if alpha / n < th.min_alpha_ratio:
        reasons.append("low_alpha")
    if digit / n > th.max_digit_ratio:
        reasons.append("high_digit")
    if symbol / n > th.max_symbol_ratio:
        reasons.append("high_symbol")

    if len(words) >= th.repetition_min_words:
        top = max(_word_counts(words).values())
        if top / len(words) > th.max_top_word_ratio:
            reasons.append("repetitive")
    return reasons


def _word_counts(words: Iterable[str]) -> dict:
    counts: dict = {}
    for w in words:
        counts[w] = counts.get(w, 0) + 1
    return counts


def text_quality_ok(text: str, th: QualityThresholds = DEFAULT_THRESHOLDS) -> bool:
    return not text_quality_reasons(text, th)


# --------------------------------------------------------------------------- #
# Autogenerated / minified detection (mostly code)
# --------------------------------------------------------------------------- #
_AUTOGEN_MARKERS = (
    "do not edit", "do not modify", "auto-generated", "autogenerated",
    "automatically generated", "@generated", "code generated by", "this file is generated",
    "generated by protoc", "generated by the protocol buffer",
)


def looks_autogenerated(text: str) -> bool:
    """Boilerplate "do not edit" / "@generated" headers, or near-total line duplication."""
    head = text[:2000].lower()
    if any(m in head for m in _AUTOGEN_MARKERS):
        return True
    lines = [ln for ln in text.splitlines() if ln.strip()]
    if len(lines) >= 20:
        uniq = len(set(lines))
        if uniq / len(lines) < 0.2:        # >80% duplicate lines
            return True
    return False


def looks_minified(text: str, *, max_line_len: int = 1000,
                   min_whitespace_ratio: float = 0.10) -> bool:
    """Minified files pack into very long lines with almost no whitespace."""
    if not text:
        return False
    longest = max((len(ln) for ln in text.splitlines()), default=len(text))
    ws = sum(c.isspace() for c in text) / len(text)
    return longest > max_line_len and ws < min_whitespace_ratio


# --------------------------------------------------------------------------- #
# Secret / PII scrubbing
# --------------------------------------------------------------------------- #
_SCRUBBERS: Tuple[Tuple[re.Pattern, str], ...] = (
    (re.compile(r"-----BEGIN (?:RSA |EC |OPENSSH |DSA |PGP )?PRIVATE KEY-----"
                r".*?-----END (?:RSA |EC |OPENSSH |DSA |PGP )?PRIVATE KEY-----",
                re.DOTALL), "[PRIVATE_KEY]"),
    (re.compile(r"\bAKIA[0-9A-Z]{16}\b"), "[AWS_KEY]"),
    (re.compile(r"\bgh[pousr]_[A-Za-z0-9]{30,}\b"), "[GITHUB_TOKEN]"),
    (re.compile(r"\bxox[baprs]-[A-Za-z0-9-]{10,}\b"), "[SLACK_TOKEN]"),
    (re.compile(r"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}"), "[EMAIL]"),
    (re.compile(r"(?i)\b(api[_-]?key|secret|token|password|passwd|pwd)\b"
                r"(\s*[:=]\s*)(['\"]?)[A-Za-z0-9_\-./+]{12,}\3"),
     r"\1\2[REDACTED]"),
)


def scrub_secrets(text: str) -> Tuple[str, int]:
    """Redact common secrets/keys/PII to placeholders. Returns (scrubbed_text, n_redactions)."""
    total = 0
    out = text
    for pat, repl in _SCRUBBERS:
        out, n = pat.subn(repl, out)
        total += n
    return out, total


# --------------------------------------------------------------------------- #
# Stats + the composed record filter
# --------------------------------------------------------------------------- #
@dataclass
class FilterStats:
    """Per-stage drop/scrub counters (mirrors the tokenize stats dicts)."""

    seen: int = 0
    kept: int = 0
    dropped_short: int = 0
    dropped_quality: int = 0
    dropped_license: int = 0
    dropped_minified: int = 0
    dropped_autogen: int = 0
    docs_scrubbed: int = 0
    secrets_scrubbed: int = 0

    def as_dict(self) -> dict:
        return {k: getattr(self, k) for k in (
            "seen", "kept", "dropped_short", "dropped_quality", "dropped_license",
            "dropped_minified", "dropped_autogen", "docs_scrubbed", "secrets_scrubbed")}


def filter_record(record: Record, *, min_chars: int = 1, quality: bool = False,
                  license_filter: bool = False, drop_minified: bool = False,
                  drop_autogen: bool = False, scrub: bool = False,
                  thresholds: QualityThresholds = DEFAULT_THRESHOLDS,
                  stats: Optional[FilterStats] = None) -> Optional[Record]:
    """Apply the enabled Stage-3 filters to one record. Returns the (possibly scrubbed)
    record, or ``None`` if it is dropped. Counts land in ``stats`` when provided."""
    if stats is not None:
        stats.seen += 1

    if len(record.text) < min_chars:
        if stats is not None:
            stats.dropped_short += 1
        return None

    if license_filter and not license_ok(record):
        if stats is not None:
            stats.dropped_license += 1
        return None

    code = is_code_record(record)
    if drop_minified and code and looks_minified(record.text):
        if stats is not None:
            stats.dropped_minified += 1
        return None
    if drop_autogen and code and looks_autogenerated(record.text):
        if stats is not None:
            stats.dropped_autogen += 1
        return None

    # Quality heuristics are for TEXT (curated code passes the gate already).
    if quality and not code and not text_quality_ok(record.text, thresholds):
        if stats is not None:
            stats.dropped_quality += 1
        return None

    if scrub:
        scrubbed, n = scrub_secrets(record.text)
        if n:
            meta = dict(record.meta)
            meta["secrets_scrubbed"] = int(meta.get("secrets_scrubbed", 0)) + n
            record = Record(text=scrubbed, source=record.source, lang=record.lang,
                            license=record.license, meta=meta)
            if stats is not None:
                stats.docs_scrubbed += 1
                stats.secrets_scrubbed += n

    if stats is not None:
        stats.kept += 1
    return record


def filter_records(records: Iterable[Record], *, min_chars: int = 1, quality: bool = False,
                   license_filter: bool = False, drop_minified: bool = False,
                   drop_autogen: bool = False, scrub: bool = False,
                   thresholds: QualityThresholds = DEFAULT_THRESHOLDS,
                   stats: Optional[FilterStats] = None) -> Iterator[Record]:
    """Stream records through the enabled Stage-3 filters (see ``filter_record``)."""
    for r in records:
        out = filter_record(r, min_chars=min_chars, quality=quality,
                            license_filter=license_filter, drop_minified=drop_minified,
                            drop_autogen=drop_autogen, scrub=scrub, thresholds=thresholds,
                            stats=stats)
        if out is not None:
            yield out
